In [48]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
import matplotlib.pyplot as plt

import wordcloud
from wordcloud import WordCloud
import json
import folium
%matplotlib inline
# 한글 설정
# pip install koreanize_matplotlib
plt.rc('font', family='Malgun Gothic')
plt.rc('axes', unicode_minus=False)
root = 'C:/workspace/python/project/data/'

# 전처리 완료한 데이터파일 이동경로
pre_root = 'C:/workspace/python/project/data/_전처리/'

# 구글드라이브 : https://drive.google.com/drive/folders/1zIzm1o8-3uxcWSU2DoWpB8aV0Oxdfz_P?usp=sharing

In [49]:
'''
                         /////--     데이터 불러오기     --/////
'''
# 공원
park_2015_df = pd.read_csv(pre_root + '공원_Data/전처리_공원수_2015.csv', encoding = 'cp949')
park_2016_df = pd.read_csv(pre_root + '공원_Data/전처리_공원수_2016.csv', encoding = 'cp949')
park_2017_df = pd.read_csv(pre_root + '공원_Data/전처리_공원수_2017.csv', encoding = 'cp949')
park_2018_df = pd.read_csv(pre_root + '공원_Data/전처리_공원수_2018.csv', encoding = 'cp949')
park_2019_df = pd.read_csv(pre_root + '공원_Data/전처리_공원수_2019.csv', encoding = 'cp949')
park_2020_df = pd.read_csv(pre_root + '공원_Data/전처리_공원수_2020.csv', encoding = 'cp949')

park_2021_df = pd.read_csv(pre_root + '공원_Data/전처리_공원수_2021.csv', encoding = 'cp949')
park_2022_df = pd.read_csv(pre_root + '공원_Data/전처리_공원수_2022.csv', encoding = 'cp949')
park_2023_df = pd.read_csv(pre_root + '공원_Data/전처리_공원수_2023.csv', encoding = 'cp949')

# 교통
## 버스
bus_2019_df = pd.read_csv(pre_root + '교통_Data/전처리_버스수_2019.csv', encoding = 'cp949')
bus_2020_df = pd.read_csv(pre_root + '교통_Data/전처리_버스수_2020.csv', encoding = 'cp949')

bus_2021_df = pd.read_csv(pre_root + '교통_Data/전처리_버스수_2021.csv', encoding = 'cp949')
bus_2022_df = pd.read_csv(pre_root + '교통_Data/전처리_버스수_2022.csv', encoding = 'cp949')
bus_2023_df = pd.read_csv(pre_root + '교통_Data/전처리_버스수_2023.csv', encoding = 'cp949')
## 지하철
train_2015_df = pd.read_csv(pre_root + '교통_Data/전처리_지하철수_2015.csv', encoding = 'cp949')
train_2020_df = pd.read_csv(pre_root + '교통_Data/전처리_지하철수_2020.csv', encoding = 'cp949')

train_2021_df = pd.read_csv(pre_root + '교통_Data/전처리_지하철수_2021.csv', encoding = 'cp949')
train_2022_df = pd.read_csv(pre_root + '교통_Data/전처리_지하철수_2022.csv', encoding = 'cp949')
train_2023_df = pd.read_csv(pre_root + '교통_Data/전처리_지하철수_2023.csv', encoding = 'cp949')

# 부동산
## 서울시 집값
house_2015_df = pd.read_csv(pre_root + '부동산_Data/전처리_부동산_2015.csv', encoding = 'cp949')
house_2016_df = pd.read_csv(pre_root + '부동산_Data/전처리_부동산_2016.csv', encoding = 'cp949')
house_2017_df = pd.read_csv(pre_root + '부동산_Data/전처리_부동산_2017.csv', encoding = 'cp949')
house_2018_df = pd.read_csv(pre_root + '부동산_Data/전처리_부동산_2018.csv', encoding = 'cp949')
house_2019_df = pd.read_csv(pre_root + '부동산_Data/전처리_부동산_2019.csv', encoding = 'cp949')
house_2020_df = pd.read_csv(pre_root + '부동산_Data/전처리_부동산_2020.csv', encoding = 'cp949')

house_2021_df = pd.read_csv(pre_root + '부동산_Data/전처리_부동산_2021.csv', encoding = 'cp949')
house_2022_df = pd.read_csv(pre_root + '부동산_Data/전처리_부동산_2022.csv', encoding = 'cp949')
house_2023_df = pd.read_csv(pre_root + '부동산_Data/전처리_부동산_2023.csv', encoding = 'cp949')
## 개발계획
develop_2015_df = pd.read_csv(pre_root + '부동산_Data/전처리_개발계획_2015.csv', encoding = 'cp949')
develop_2016_df = pd.read_csv(pre_root + '부동산_Data/전처리_개발계획_2016.csv', encoding = 'cp949')
develop_2017_df = pd.read_csv(pre_root + '부동산_Data/전처리_개발계획_2017.csv', encoding = 'cp949')
develop_2018_df = pd.read_csv(pre_root + '부동산_Data/전처리_개발계획_2018.csv', encoding = 'cp949')
develop_2019_df = pd.read_csv(pre_root + '부동산_Data/전처리_개발계획_2019.csv', encoding = 'cp949')
develop_2020_df = pd.read_csv(pre_root + '부동산_Data/전처리_개발계획_2020.csv', encoding = 'cp949')

develop_2021_df = pd.read_csv(pre_root + '부동산_Data/전처리_개발계획_2021.csv', encoding = 'cp949')
develop_2022_df = pd.read_csv(pre_root + '부동산_Data/전처리_개발계획_2022.csv', encoding = 'cp949')
develop_2023_df = pd.read_csv(pre_root + '부동산_Data/전처리_개발계획_2023.csv', encoding = 'cp949')

# 수요공급
demandSupply_2015_df = pd.read_csv(pre_root + '수요공급_Data/전처리_수요공급지수_2015.csv', encoding = 'cp949')
demandSupply_2016_df = pd.read_csv(pre_root + '수요공급_Data/전처리_수요공급지수_2016.csv', encoding = 'cp949')
demandSupply_2017_df = pd.read_csv(pre_root + '수요공급_Data/전처리_수요공급지수_2017.csv', encoding = 'cp949')
demandSupply_2018_df = pd.read_csv(pre_root + '수요공급_Data/전처리_수요공급지수_2018.csv', encoding = 'cp949')
demandSupply_2019_df = pd.read_csv(pre_root + '수요공급_Data/전처리_수요공급지수_2019.csv', encoding = 'cp949')
demandSupply_2020_df = pd.read_csv(pre_root + '수요공급_Data/전처리_수요공급지수_2020.csv', encoding = 'cp949')

demandSupply_2021_df = pd.read_csv(pre_root + '수요공급_Data/전처리_수요공급지수_2021.csv', encoding = 'cp949')
demandSupply_2022_df = pd.read_csv(pre_root + '수요공급_Data/전처리_수요공급지수_2022.csv', encoding = 'cp949')
demandSupply_2023_df = pd.read_csv(pre_root + '수요공급_Data/전처리_수요공급지수_2023.csv', encoding = 'cp949')

# 유통업체
distribute_2015_df = pd.read_csv(pre_root + '유통업체_Data/전처리_유통업체_2015.csv', encoding = 'cp949')
distribute_2016_df = pd.read_csv(pre_root + '유통업체_Data/전처리_유통업체_2016.csv', encoding = 'cp949')
distribute_2017_df = pd.read_csv(pre_root + '유통업체_Data/전처리_유통업체_2017.csv', encoding = 'cp949')
distribute_2018_df = pd.read_csv(pre_root + '유통업체_Data/전처리_유통업체_2018.csv', encoding = 'cp949')
distribute_2019_df = pd.read_csv(pre_root + '유통업체_Data/전처리_유통업체_2019.csv', encoding = 'cp949')
distribute_2020_df = pd.read_csv(pre_root + '유통업체_Data/전처리_유통업체_2020.csv', encoding = 'cp949')

distribute_2021_df = pd.read_csv(pre_root + '유통업체_Data/전처리_유통업체_2021.csv', encoding = 'cp949')
distribute_2022_df = pd.read_csv(pre_root + '유통업체_Data/전처리_유통업체_2022.csv', encoding = 'cp949')
distribute_2023_df = pd.read_csv(pre_root + '유통업체_Data/전처리_유통업체_2023.csv', encoding = 'cp949')

# 의료기관
hospital_2015_df = pd.read_csv(pre_root + '의료기관_Data/전처리_병원수_2015.csv', encoding = 'cp949')
hospital_2016_df = pd.read_csv(pre_root + '의료기관_Data/전처리_병원수_2016.csv', encoding = 'cp949')
hospital_2017_df = pd.read_csv(pre_root + '의료기관_Data/전처리_병원수_2017.csv', encoding = 'cp949')
hospital_2018_df = pd.read_csv(pre_root + '의료기관_Data/전처리_병원수_2018.csv', encoding = 'cp949')
hospital_2019_df = pd.read_csv(pre_root + '의료기관_Data/전처리_병원수_2019.csv', encoding = 'cp949')
hospital_2020_df = pd.read_csv(pre_root + '의료기관_Data/전처리_병원수_2020.csv', encoding = 'cp949')

hospital_2021_df = pd.read_csv(pre_root + '의료기관_Data/전처리_병원수_2021.csv', encoding = 'cp949')
hospital_2022_df = pd.read_csv(pre_root + '의료기관_Data/전처리_병원수_2022.csv', encoding = 'cp949')
hospital_2023_df = pd.read_csv(pre_root + '의료기관_Data/전처리_병원수_2023.csv', encoding = 'cp949')

# 인구수
population_2015_df = pd.read_csv(pre_root + '인구수_Data/전처리_인구수_2015.csv', encoding = 'cp949')
population_2016_df = pd.read_csv(pre_root + '인구수_Data/전처리_인구수_2016.csv', encoding = 'cp949')
population_2017_df = pd.read_csv(pre_root + '인구수_Data/전처리_인구수_2017.csv', encoding = 'cp949')
population_2018_df = pd.read_csv(pre_root + '인구수_Data/전처리_인구수_2018.csv', encoding = 'cp949')
population_2019_df = pd.read_csv(pre_root + '인구수_Data/전처리_인구수_2019.csv', encoding = 'cp949')
population_2020_df = pd.read_csv(pre_root + '인구수_Data/전처리_인구수_2020.csv', encoding = 'cp949')

population_2021_df = pd.read_csv(pre_root + '인구수_Data/전처리_인구수_2021.csv', encoding = 'cp949')
population_2022_df = pd.read_csv(pre_root + '인구수_Data/전처리_인구수_2022.csv', encoding = 'cp949')
population_2023_df = pd.read_csv(pre_root + '인구수_Data/전처리_인구수_2023.csv', encoding = 'cp949')

# 주거실태 (거래량)
volume_2015_df = pd.read_csv(pre_root + '주거실태_Data/전처리_거래량_2015.csv', encoding = 'cp949')
volume_2016_df = pd.read_csv(pre_root + '주거실태_Data/전처리_거래량_2016.csv', encoding = 'cp949')
volume_2017_df = pd.read_csv(pre_root + '주거실태_Data/전처리_거래량_2017.csv', encoding = 'cp949')
volume_2018_df = pd.read_csv(pre_root + '주거실태_Data/전처리_거래량_2018.csv', encoding = 'cp949')
volume_2019_df = pd.read_csv(pre_root + '주거실태_Data/전처리_거래량_2019.csv', encoding = 'cp949')
volume_2020_df = pd.read_csv(pre_root + '주거실태_Data/전처리_거래량_2020.csv', encoding = 'cp949')

volume_2021_df = pd.read_csv(pre_root + '주거실태_Data/전처리_거래량_2021.csv', encoding = 'cp949')
volume_2022_df = pd.read_csv(pre_root + '주거실태_Data/전처리_거래량_2022.csv', encoding = 'cp949')
volume_2023_df = pd.read_csv(pre_root + '주거실태_Data/전처리_거래량_2023.csv', encoding = 'cp949')

# 주거실태
abode_house_2015_df = pd.read_csv(pre_root + '주거실태_Data/전처리_주거실태_2015.csv', encoding = 'cp949')
abode_house_2016_df = pd.read_csv(pre_root + '주거실태_Data/전처리_주거실태_2016.csv', encoding = 'cp949')
abode_house_2017_df = pd.read_csv(pre_root + '주거실태_Data/전처리_주거실태_2017.csv', encoding = 'cp949')
abode_house_2018_df = pd.read_csv(pre_root + '주거실태_Data/전처리_주거실태_2018.csv', encoding = 'cp949')
abode_house_2019_df = pd.read_csv(pre_root + '주거실태_Data/전처리_주거실태_2019.csv', encoding = 'cp949')
abode_house_2020_df = pd.read_csv(pre_root + '주거실태_Data/전처리_주거실태_2020.csv', encoding = 'cp949')

abode_house_2021_df = pd.read_csv(pre_root + '주거실태_Data/전처리_주거실태_2021.csv', encoding = 'cp949')
abode_house_2022_df = pd.read_csv(pre_root + '주거실태_Data/전처리_주거실태_2022.csv', encoding = 'cp949')
abode_house_2023_df = pd.read_csv(pre_root + '주거실태_Data/전처리_주거실태_2023.csv', encoding = 'cp949')

# 매매가격지수
priceRelative_2015_df = pd.read_csv(pre_root + '수요공급_Data/전처리_매매가격지수_2015.csv', encoding = 'cp949')
priceRelative_2016_df = pd.read_csv(pre_root + '수요공급_Data/전처리_매매가격지수_2016.csv', encoding = 'cp949')
priceRelative_2017_df = pd.read_csv(pre_root + '수요공급_Data/전처리_매매가격지수_2017.csv', encoding = 'cp949')
priceRelative_2018_df = pd.read_csv(pre_root + '수요공급_Data/전처리_매매가격지수_2018.csv', encoding = 'cp949')
priceRelative_2019_df = pd.read_csv(pre_root + '수요공급_Data/전처리_매매가격지수_2019.csv', encoding = 'cp949')
priceRelative_2020_df = pd.read_csv(pre_root + '수요공급_Data/전처리_매매가격지수_2020.csv', encoding = 'cp949')

priceRelative_2021_df = pd.read_csv(pre_root + '수요공급_Data/전처리_매매가격지수_2021.csv', encoding = 'cp949')
priceRelative_2022_df = pd.read_csv(pre_root + '수요공급_Data/전처리_매매가격지수_2022.csv', encoding = 'cp949')
priceRelative_2023_df = pd.read_csv(pre_root + '수요공급_Data/전처리_매매가격지수_2023.csv', encoding = 'cp949')

print('데이터 프레임 삽입 완료..!!')

데이터 프레임 삽입 완료..!!

In [50]:
'''
                         /////--     데이터 병합 함수     --/////
          공원, 버스, 지하철, 부동산, 개발계획, 수요공급, 유통업체, 의료기관, 인구수, 거래량
'''
def merge_year_dataFrame(park_df, bus_df, train_df, house_df, develop_df, demandSupply_df,
                         distribute_df, hospital_df, population_df, volume_df,
                         abode_house_df, priceRelative_df, year) :
  # 공원
  park_df = park_df[['구', '합계_공원수 (개소)']].rename(columns = {'합계_공원수 (개소)' : '합계_공원수'})
  
  # 버스
  if bus_df.drop(columns=['구'], axis=1).isnull().all().all() : 
    bus_df = pd.DataFrame({'구' : house_2021_df['구'], '버스 수' : np.nan})  
  else : 
    bus_df = bus_df['구'].value_counts().reset_index().rename(columns = {'count' : '버스 수'})
  
  # 지하철
  train_df = train_df[['구', '역개수']]
  
  # 부동산
  house_df = house_df[['구', '평균시세']]
  
  # 개발계획
  develop_df = develop_df[['구', '계_구역수 (개)']].rename(columns = {'계_구역수 (개)' : '개발계획_합계'})
  
  # 수요공급
  demandSupply_df = round(demandSupply_df.groupby('구')['수급등급'].mean(), 2).reset_index().rename(columns = {'수급등급' : '수요공급지수'})
  
  # 유통업체
  distribute_df = distribute_df.iloc[1:, :].reset_index(drop = True)
  condition = distribute_df.columns.str.contains('_개소') # 원하는 컬럼만 조회
  condition[0] = True
  distribute_df = distribute_df.loc[:, condition]
  column_names = {} # 컬럼 이름 변경용 딕셔너리
  columns = distribute_df.columns
  for column in columns :
    column_names[column] = column.split('_개소')[0]
  distribute_df = distribute_df.rename(columns = column_names)
  distribute_df = distribute_df.replace('-', 0)
  
  # 의료기관
  hospital_df = hospital_df[['구', '소계_병원수']].rename(columns = {'소계_병원수' : '병원수'})
  hospital_df = hospital_df.iloc[1:, :].reset_index(drop = True)
  
  # 인구수
  population_df
  
  # 주거실태 (거래량)
  volume_df = volume_df.drop(columns = '년도').rename(columns = {'동(호)수' : '거래량'})[['구', '거래량']]

  # 주거실태
  abode_house_df = abode_house_df.drop(columns = '년도')

  # 매매가격지수 (증감률)
  priceRelative_df = priceRelative_df.drop(columns = '원자료')

  dfs = [park_df, bus_df, train_df, develop_df,
         demandSupply_df, distribute_df, hospital_df,
         population_df, volume_df, abode_house_df, priceRelative_df]  # 필요한 데이터프레임 추가
  result = house_df.copy()
  
  ### 데이터 병합
  for df in dfs : 
    # 병합
    result = result.merge(df, on='구', how='left')

  result['연도'] = year

  result = result.rename(columns={'계' : '주택_합계'})

  return result

                    #######                            #######
                    ##  데이터프레임 데이터 타입 변환 함수  ##
                    #######                            #######
def df_to_float(df) : 
  df['대형마트'] = df['대형마트'].astype(float)
  df['백화점'] = df['백화점'].astype(float)
  df['전문점'] = df['전문점'].astype(float)
  df['쇼핑센터'] = df['쇼핑센터'].astype(float)
  df['복합쇼핑몰'] = df['복합쇼핑몰'].astype(float)
  return df

                    #######                                           #######
                    ##  아무것도 없는 컬럼 수만 동일한 데이터프레임 생성   ##
                    #######                                           #######
def copy_none_df( df) : 
  copy_df = df.copy()
  column_names = copy_df.columns
  for column in column_names :
    copy_df[column] = np.nan
  copy_df['구'] = df['구']
  return copy_df

                    #######                                            #######
                    ##  컬럼별 연도에 따라 비어있는 행 상대적 평균치 적용   ##
                    #######                                            #######
def fillna_with_neighbor_mean(df, column, year_column):
  """
  NaN 값을 인접 연도의 평균값으로 채우는 함수.
  
  Parameters:
  - df: 데이터프레임
  - column: NaN 값을 채울 컬럼 이름
  - year_column: 연도를 나타내는 컬럼 이름
  
  Returns:
  - NaN이 채워진 데이터프레임
  """
  # NaN이 있는 연도와 없는 연도 분리
  null_years = df.loc[df[column].isna(), year_column].unique()
  not_null_years = df.loc[~df[column].isna(), year_column].unique()

  # 연도별 평균값 계산
  year_means = df.groupby(year_column)[column].mean()

  # NaN 채우기
  for null_year in null_years:
    # null_year 보다 큰 not_null_year 중 가장 작은 연도
    next_year = not_null_years[not_null_years > null_year].min() if (not_null_years > null_year).any() else None
    # null_year 보다 작은 not_null_year 중 가장 큰 연도
    prev_year = not_null_years[not_null_years < null_year].max() if (not_null_years < null_year).any() else None

    # 평균값 계산
    if prev_year is not None and next_year is not None:
        fill_value = (year_means[prev_year] + year_means[next_year]) / 2
    elif next_year is not None:
        fill_value = year_means[next_year]
    elif prev_year is not None:
        fill_value = year_means[prev_year]
    else:
        fill_value = np.nan  # 채울 수 없는 경우 NaN 유지

    # NaN 채우기
    df.loc[(df[year_column] == null_year) & (df[column].isna()), column] = fill_value

  return df

In [51]:
'''
                              /////--     데이터 부족     --/////
          버스    :    2015, 2016, 2017, 2018 없음    / 2019 ~ 2023 있음
          지하철  :    2016, 2017, 2018, 2019 없음    / 2015, 2020 ~ 2023 있음

          없는 데이터 Null 값으로 임의의 데이터프레임 삽입 후 평균치로 null값 처리할 예정
'''
bus_null_df = copy_none_df(bus_2021_df) # 컬럼명과 개수만 가져옴
train_null_df = copy_none_df(train_2021_df) # 컬럼명과 개수만 가져옴

In [52]:
'''
                              /////--     데이터 병합     --/////
          공원, 버스, 지하철, 부동산, 개발계획, 수요공급, 유통업체, 의료기관, 인구수, 거래량
'''
merge_year_2015 = merge_year_dataFrame(park_2015_df, bus_null_df, train_2015_df, house_2015_df,
                                       develop_2015_df, demandSupply_2015_df, distribute_2015_df,
                                       hospital_2015_df, population_2015_df, volume_2015_df,
                                       abode_house_2015_df, priceRelative_2015_df,
                                       year = 2015)

merge_year_2016 = merge_year_dataFrame(park_2016_df, bus_null_df, train_null_df, house_2016_df,
                                       develop_2016_df, demandSupply_2016_df, distribute_2016_df,
                                       hospital_2016_df, population_2016_df, volume_2016_df,
                                       abode_house_2016_df, priceRelative_2016_df,
                                       year = 2016)

merge_year_2017 = merge_year_dataFrame(park_2017_df, bus_null_df, train_null_df, house_2017_df,
                                       develop_2017_df, demandSupply_2017_df, distribute_2017_df,
                                       hospital_2017_df, population_2017_df, volume_2017_df,
                                       abode_house_2017_df, priceRelative_2017_df,
                                       year = 2017)

merge_year_2018 = merge_year_dataFrame(park_2018_df, bus_null_df, train_null_df, house_2018_df,
                                       develop_2018_df, demandSupply_2018_df, distribute_2018_df,
                                       hospital_2018_df, population_2018_df, volume_2018_df,
                                       abode_house_2018_df, priceRelative_2018_df,
                                       year = 2018)

merge_year_2019 = merge_year_dataFrame(park_2019_df, bus_2019_df, train_null_df, house_2019_df,
                                       develop_2019_df, demandSupply_2019_df, distribute_2019_df,
                                       hospital_2019_df, population_2019_df, volume_2019_df,
                                       abode_house_2019_df, priceRelative_2019_df,
                                       year = 2019)

merge_year_2020 = merge_year_dataFrame(park_2020_df, bus_2020_df, train_2020_df, house_2020_df,
                                       develop_2020_df, demandSupply_2020_df, distribute_2020_df,
                                       hospital_2020_df, population_2020_df, volume_2020_df,
                                       abode_house_2020_df, priceRelative_2020_df,
                                       year = 2020)


merge_year_2021 = merge_year_dataFrame(park_2021_df, bus_2021_df, train_2021_df, house_2021_df,
                                       develop_2021_df, demandSupply_2021_df, distribute_2021_df,
                                       hospital_2021_df, population_2021_df, volume_2021_df,
                                       abode_house_2021_df, priceRelative_2021_df,
                                       year = 2021)

merge_year_2022 = merge_year_dataFrame(park_2022_df, bus_2022_df, train_2022_df, house_2022_df,
                                       develop_2022_df, demandSupply_2022_df, distribute_2022_df,
                                       hospital_2022_df, population_2022_df, volume_2022_df,
                                       abode_house_2022_df, priceRelative_2022_df,
                                       year = 2022)

merge_year_2023 = merge_year_dataFrame(park_2023_df, bus_2023_df, train_2023_df, house_2023_df,
                                       develop_2023_df, demandSupply_2023_df, distribute_2023_df,
                                       hospital_2023_df, population_2023_df, volume_2023_df,
                                       abode_house_2023_df, priceRelative_2023_df,
                                       year = 2023)

In [53]:
'''
                              /////--     머신러닝용 데이터 결합     --/////
'''
concat_list = [merge_year_2015, merge_year_2016, merge_year_2017, merge_year_2018,
               merge_year_2019, merge_year_2020, merge_year_2021, merge_year_2022,
               merge_year_2023]
ai_concat = pd.concat(concat_list, ignore_index = True)
ai_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 27 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   구          225 non-null    object
 1   평균시세       225 non-null    float64
 2   합계_공원수     225 non-null    int64
 3   버스 수       125 non-null    float64
 4   역개수        125 non-null    float64
 5   개발계획_합계    225 non-null    int64
 6   수요공급지수     225 non-null    float64
 7   합계         225 non-null    int64
 8   대형마트       225 non-null    object
 9   백화점        225 non-null    object
 10  전문점        225 non-null    object
 11  쇼핑센터       225 non-null    object
 12  복합쇼핑몰      225 non-null    object
 13  그밖의 대규모점포  225 non-null    int64
 14  병원수        225 non-null    int64
 15  총인구        225 non-null    int64
 16  내국인-계      225 non-null    int64
 17  외국인-계      225 non-null    int64
 18  거래량        225 non-null    int64
 19  주택_합계      225 non-null    int64
 20  단독주택       225 non-null    int64
 21  아파트        225 non-null    int64
 22  연립주택       225 non-null    int64
 23  다세대주택      225 non-null    int64
 24  비주거용주택     225 non-null    int64
 25  전기대비증감률    225 non-null    float64
 26  연도         225 non-null    int64
dtypes: float64(5), int64(16), object(6)
memory usage: 47.6+ KB

In [54]:
ai_concat = fillna_with_neighbor_mean(ai_concat, '버스 수', '연도')
ai_concat = fillna_with_neighbor_mean(ai_concat, '역개수', '연도')

In [55]:
# 특정 데이터 타입 실수형으로 전환
ai_concat = df_to_float(ai_concat)

In [56]:
# 평균시세 값을 천만원 단위로 변환
# 평균시세 값이 너무 크면 오차도 너무 크게 나오기 때문
ai_concat['평균시세'] = round(ai_concat['평균시세'] / 10000, 6)

# 컬럼명을 '평균시세(천만원)'으로 변경
ai_concat.rename(columns={'평균시세': '평균시세(천만원)'}, inplace=True)

In [57]:
ai_concat.isna().sum()
ai_concat.info()
ai_concat[:20]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 27 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   구          225 non-null    object
 1   평균시세(천만원)  225 non-null    float64
 2   합계_공원수     225 non-null    int64
 3   버스 수       225 non-null    float64
 4   역개수        225 non-null    float64
 5   개발계획_합계    225 non-null    int64
 6   수요공급지수     225 non-null    float64
 7   합계         225 non-null    int64
 8   대형마트       225 non-null    float64
 9   백화점        225 non-null    float64
 10  전문점        225 non-null    float64
 11  쇼핑센터       225 non-null    float64
 12  복합쇼핑몰      225 non-null    float64
 13  그밖의 대규모점포  225 non-null    int64
 14  병원수        225 non-null    int64
 15  총인구        225 non-null    int64
 16  내국인-계      225 non-null    int64
 17  외국인-계      225 non-null    int64
 18  거래량        225 non-null    int64
 19  주택_합계      225 non-null    int64
 20  단독주택       225 non-null    int64
 21  아파트        225 non-null    int64
 22  연립주택       225 non-null    int64
 23  다세대주택      225 non-null    int64
 24  비주거용주택     225 non-null    int64
 25  전기대비증감률    225 non-null    float64
 26  연도         225 non-null    int64
dtypes: float64(10), int64(16), object(1)
memory usage: 47.6+ KB

,구,평균시세(천만원),합계_공원수,버스 수,역개수,개발계획_합계,수요공급지수,합계,대형마트,백화점,...,외국인-계,거래량,주택_합계,단독주택,아파트,연립주택,다세대주택,비주거용주택,전기대비증감률,연도
0,강남구,8.247352,154,450.4,21.0,15,101.32,32,1.0,6.0,...,8627,19083,176654,7437,133127,6106,28122,1862,0.630000,2015
1,강동구,4.261749,122,450.4,14.0,10,101.32,16,3.0,1.0,...,6184,15566,119824,11345,78697,3704,24886,1192,0.586667,2015
2,강북구,2.712907,83,450.4,3.0,6,105.09,13,1.0,1.0,...,4238,9478,91806,19393,32651,4854,33820,1088,0.201667,2015
3,강서구,3.002400,167,450.4,9.0,17,101.95,19,4.0,1.0,...,8039,27834,179045,11671,107304,5306,53569,1195,0.402500,2015
4,관악구,3.319721,111,450.4,4.0,12,101.95,21,1.0,1.0,...,24022,12835,121277,23159,53262,6489,36436,1931,0.258333,2015
5,광진구,4.705565,56,450.4,11.0,9,105.09,19,2.0,1.0,...,17206,9293,79393,17034,29880,4434,26561,1484,0.413333,2015
6,구로구,2.934265,90,450.4,7.0,4,101.95,24,4.0,2.0,...,39461,14887,118047,12469,74594,7362,22783,839,0.491667,2015
7,금천구,2.870435,58,450.4,1.0,9,101.95,15,3.0,0.0,...,24792,10709,57096,9776,27342,3937,15549,492,0.266667,2015
8,노원구,2.785011,178,450.4,13.0,23,105.09,14,3.0,2.0,...,4726,16785,186626,8143,160725,3536,13471,751,0.600000,2015
9,도봉구,2.520588,80,450.4,3.0,12,105.09,9,3.0,0.0,...,2554,10661,102443,9404,64082,4242,24014,701,0.329167,2015
10,동대문구,3.402476,99,450.4,6.0,13,105.09,23,2.0,2.0,...,14830,13019,98203,20799,59534,3740,12529,1601,0.484167,2015
11,동작구,4.179439,82,450.4,12.0,17,101.95,6,0.0,1.0,...,14925,12429,109362,17113,56969,5475,28726,1079,0.286667,2015
12,마포구,4.573422,155,450.4,16.0,9,76.35,15,3.0,0.0,...,11455,17254,116135,14302,63071,3683,33508,1571,0.236667,2015
13,서대문구,3.698362,120,450.4,5.0,8,76.35,9,0.0,1.0,...,11007,11912,92885,15568,45340,5762,25250,965,0.225833,2015
14,서초구,8.090298,147,450.4,12.0,10,101.32,27,3.0,2.0,...,7109,14388,125403,6773,90084,5722,21474,1350,0.500000,2015
15,성동구,5.074810,81,450.4,14.0,12,105.09,12,2.0,0.0,...,9869,11797,82331,11250,59331,2076,8610,1064,0.462500,2015
16,성북구,3.665283,130,450.4,9.0,12,105.09,11,3.0,1.0,...,11134,14754,128046,27180,69725,6518,23097,1526,0.259167,2015
17,송파구,5.504388,147,450.4,28.0,15,101.32,24,5.0,2.0,...,9746,18452,187030,10231,111685,5040,58287,1787,0.363333,2015
18,양천구,3.911782,119,450.4,5.0,11,101.95,14,2.0,2.0,...,5847,14355,134097,9907,83827,4459,34948,956,0.360000,2015
19,영등포구,3.925921,122,450.4,11.0,27,101.95,27,5.0,2.0,...,49044,15375,96195,17306,65088,1562,11112,1127,0.383333,2015

In [58]:
'''
              ///////    선택 1)   21 ~ 23 년도 데이터를 전부 섞은 후    ///////
                   8 : 2 비율로 무작위로 나눠서 훈련용, 테스트용으로 분리하기
'''
from sklearn.model_selection import train_test_split

# 독립변수와 종속변수 분리
X = ai_concat.drop(columns=['평균시세(천만원)', '구', '연도'])  # 종속변수와 제외할 컬럼 제거
y = ai_concat['평균시세(천만원)']  # 종속변수

# 데이터 분리: 80% 훈련용, 20% 테스트용
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 확인
print("훈련 데이터 크기:", X_train.shape, y_train.shape)
print("테스트 데이터 크기:", X_test.shape, y_test.shape)

훈련 데이터 크기: (180, 24) (180,)
테스트 데이터 크기: (45, 24) (45,)

In [59]:
'''
              ///////    선택 2)   21 ~ 22 년도 데이터를 테스트 용으로    ///////
                            23 년도 데이터를 훈련용으로 분리하기
'''
# 훈련용 데이터 : 2015 ~ 2022
train_data = ai_concat[ai_concat['연도'] < 2023]

# 테스트용 데이터 : 2023
test_data = ai_concat[ai_concat['연도'] == 2023]

# X, y 분리
X_train = train_data.drop(['평균시세(천만원)', '구', '연도'], axis = 1)
y_train = train_data['평균시세(천만원)']

X_test = test_data.drop(['평균시세(천만원)', '구', '연도'], axis = 1)
y_test = test_data['평균시세(천만원)']

# 확인
print("훈련 데이터 크기:", X_train.shape, y_train.shape)
print("테스트 데이터 크기:", X_test.shape, y_test.shape)

훈련 데이터 크기: (200, 24) (200,)
테스트 데이터 크기: (25, 24) (25,)